version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  express:
    build: server
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: frontend
    ports:
      - "4200:4200"
